### PR TITLE
Enable ErrorProne DefaultCharset

### PR DESCRIPTION
**Pull request by ebyhr**
# Description

Enable ErrorProne [DefaultCharset](https://errorprone.info/bugpattern/DefaultCharset)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

Please delete options that are not relevant.

- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] If adding new functionality, I have discussed my implementation with the community using the linked GitHub issue
- [x] I have signed and submitted the [ICLA](https://github.com/polaris-catalog/polaris/blob/main/ICLA.md) and if needed, the [CCLA](https://github.com/polaris-catalog/polaris/blob/main/CCLA.md). See [Contributing](https://github.com/polaris-catalog/polaris/blob/main/CONTRIBUTING.md) for details.

### CODE REVIEW

**Comment by flyrain** [comment]
Thanks @ebyhr for the PR. Can we use the Java system property for this?  So that we set the project level default encoding in one place. 
```
file.encoding: UTF-8
```

**Comment by ebyhr** [comment]
@flyrain Could you let me know the place where JVM options are managed in this project?

**Comment by flyrain** [comment]
Something like this in `build.gradle.kts`
```
  tasks.withType(JavaCompile.class).configureEach {
    options.encoding = "UTF-8"
  }
```

**Comment by ebyhr** [comment]
Does the option ensure the runtime encoding? Sorry for my basic quesiton, I'm unfamiliar with Gradle ecosystem because I usually use Maven.

**Comment by flyrain** [comment]
Good question. Looks like the default charset is always set at runtime. We have two options:
1. Set the jvm arg at the runtime. For example, setting it in docker file java command. This is not quite reliable since user can always have their way java command to run the application.
2. Set it in the application main like this `System.setProperty("file.encoding", "UTF-8");`. It is not recommended since the lib loaded before this line will still get the default system charset. 
3. The way your original PR proposed. 

The option 3 seems the safest way to go. There isn't any way to set the default charset at the compile time :-(. I guess we need to go with the original PR, but I'm open to any suggestion.

**Review by flyrain — APPROVED** [review]

**Comment by flyrain** [comment]
I will merge this one, if there is no better solution proposed. cc @dennishuo @collado-mike @aihuaxu @RussellSpitzer

**Comment by flyrain** [comment]
Thanks @ebyhr for the PR.

**Pull request merged**
